### ISSUE TITLE
Could not pass event PlayerPreLoginEvent to BanSystem v2.7

### ISSUE THREAD

**Issue by pavl21** [EnderKohle/BanSystem-v2#11]
```
java.lang.NullPointerException: Cannot invoke "org.json.JSONObject.getString(String)" because "jsonObject" is null
	at net.coalcube.bansystem.core.util.UUIDFetcher.getName(UUIDFetcher.java:127) ~[bansystem-2.7-SNAPSHOT.jar:?]
	at net.coalcube.bansystem.spigot.listener.PlayerConnectionListener.onPreLogin(PlayerConnectionListener.java:53) ~[bansystem-2.7-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1778]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler$1.evaluate(ServerLoginPacketListenerImpl.java:460) ~[purpur-1.19.2.jar:git-Purpur-1778]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler$1.evaluate(ServerLoginPacketListenerImpl.java:457) ~[purpur-1.19.2.jar:git-Purpur-1778]
	at org.bukkit.craftbukkit.v1_19_R1.util.Waitable.run(Waitable.java:24) ~[purpur-1.19.2.jar:git-Purpur-1778]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1533) ~[purpur-1.19.2.jar:git-Purpur-1778]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1778]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1444) ~[purpur-1.19.2.jar:git-Purpur-1778]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[purpur-1.19.2.jar:git-Purpur-1778]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1778]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Dieser Fehler kommt jedes mal, wenn ein Spieler das Spiel betritt.

**Comment by EnderKohle** [comment]
Ich habe das Problem bereits gefunden und behoben, das update dazu kommt demnächst. Vielen dank für deinen Report. Mfg
