### ISSUE TITLE
Problem mit der Kompatibilität von Bedrock-Spielern (GeyserMC) - Bedrockspieler können NICHT gebannt werden.

### ISSUE THREAD

**Issue by pavl21** [EnderKohle/BanSystem-v2#12]
```
'[23:22:18] [defaultEventLoopGroup-5-4/INFO]: [Geyser-Spigot] Princeps1528 (logged in as: Princeps1528) has connected to the Java server
[23:22:18] [Server thread/WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://sessionserver.mojang.com/session/minecraft/profile/0000000000000000000901f79f58d67d
[23:22:18] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
[23:22:18] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[23:22:18] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[23:22:18] [Server thread/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[23:22:18] [Server thread/WARN]: 	at bansystem-2.7-SNAPSHOT.jar//net.coalcube.bansystem.core.util.UUIDFetcher.readJsonFromUrl(UUIDFetcher.java:158)
[23:22:18] [Server thread/WARN]: 	at bansystem-2.7-SNAPSHOT.jar//net.coalcube.bansystem.core.util.UUIDFetcher.getName(UUIDFetcher.java:122)
[23:22:18] [Server thread/WARN]: 	at bansystem-2.7-SNAPSHOT.jar//net.coalcube.bansystem.spigot.listener.PlayerConnectionListener.onPreLogin(PlayerConnectionListener.java:53)
[23:22:18] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source)
[23:22:18] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[23:22:18] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:22:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:22:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678)
[23:22:18] [Server thread/WARN]: 	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler$1.evaluate(ServerLoginPacketListenerImpl.java:450)
[23:22:18] [Server thread/WARN]: 	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler$1.evaluate(ServerLoginPacketListenerImpl.java:447)
[23:22:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.util.Waitable.run(Waitable.java:24)
[23:22:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1533)
[23:22:18] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[23:22:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1444)
[23:22:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1214)
[23:22:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[23:22:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:22:18] [Server thread/ERROR]: Could not pass event PlayerPreLoginEvent to BanSystem v2.7
java.lang.NullPointerException: Cannot invoke "org.json.JSONObject.getString(String)" because "jsonObject" is null
	at net.coalcube.bansystem.core.util.UUIDFetcher.getName(UUIDFetcher.java:127) ~[bansystem-2.7-SNAPSHOT.jar:?]
	at net.coalcube.bansystem.spigot.listener.PlayerConnectionListener.onPreLogin(PlayerConnectionListener.java:53) ~[bansystem-2.7-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1786]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler$1.evaluate(ServerLoginPacketListenerImpl.java:450) ~[purpur-1.19.2.jar:git-Purpur-1786]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler$1.evaluate(ServerLoginPacketListenerImpl.java:447) ~[purpur-1.19.2.jar:git-Purpur-1786]
	at org.bukkit.craftbukkit.v1_19_R1.util.Waitable.run(Waitable.java:24) ~[purpur-1.19.2.jar:git-Purpur-1786]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1533) ~[purpur-1.19.2.jar:git-Purpur-1786]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1786]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1444) ~[purpur-1.19.2.jar:git-Purpur-1786]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[purpur-1.19.2.jar:git-Purpur-1786]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1786]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:22:18] [Geyser Spigot connection thread-4-1/INFO]: UUID of player .Princeps1528 is 00000000-0000-0000-0009-01f79f58d67d
[23:22:18] [Server thread/INFO]: [floodgate] Floodgate Spieler .Princeps1528 hat den Server betreten (UUID: 00000000-0000-0000-0009-01f79f58d67d)'
```

Bei jedem Login kommt dieser Fehler bei jeder Anmeldung. Ich bin mir nicht ganz sicher, ob die Anfrage auch vom BanSystem kommt, aber der Fehler weiter unten tritt beim Bansystem auf..

**Comment by pavl21** [comment]
Weder mit der UUID noch mit dem Spielernamen ist es nicht möglich, den Spieler zu bannen.

**Comment by EnderKohle** [comment]
Versuch es mit der neuen Version vom plugin. Mfg

**Comment by pavl21** [comment]
Wo ist die neue Version? In Spigot ist nur das Update von Februar.

**Comment by antisocialtobi** [comment]
Das Februar bezieht sich auf die letzte Update Nachricht. Lade dir das plugin einfach erneut runter, lass dir die Config und Massage.yml neu erstellen und wenn es nicht geht dann öffne den case einfach erneut
