### ISSUE TITLE
Error when player tries to enter server

### ISSUE THREAD

**Issue by axin0452** [EnderKohle/BanSystem-v2#6]
[20:49:00 ERROR]: Exception in thread "Thread-23" java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
[20:49:00 ERROR]:       at net.coalcube.bansystem.bungee.listener.LoginListener.lambda$onLogin$1(LoginListener.java:54)
[20:49:00 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[20:49:00 ERROR]: Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
[20:49:00 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
[20:49:00 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[20:49:00 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[20:49:00 ERROR]:       ... 2 more

What other valid information should I provide to fix this issue

**Comment by Dotta4You** [comment]
download the plugin again from spigot and follow the install tutorial (On Discord)

**Comment by EnderKohle** [comment]
Dear axin0452,

Thank you for your report. I already have fixed the problem. You can download the newest version at https://www.spigotmc.org/resources/bansystem-mit-ids-spigot-bungeecord.65863/ .

Tobi.

**Comment by Dotta4You** [comment]
ich glaube der wird des nd mehr benutzen xDDD 2ter mai... uff xD
