### ISSUE TITLE
Mojang has removed the public methode to get the player names and now i dont can join the server

### ISSUE THREAD

**Issue by ezTxmMC** [EnderKohle/BanSystem-v2#9]
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]: java.io.FileNotFoundException: https://api.mojang.com/user/profiles/fcae1f93bc704f9f86e33cf132e1c372/names
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at net.coalcube.bansystem.core.util.UUIDFetcher.getName(UUIDFetcher.java:124)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at net.coalcube.bansystem.bungee.listener.LoginListener.lambda$onLogin$1(LoginListener.java:53)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at java.base/java.lang.Thread.run(Thread.java:833)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]: Exception in thread "Thread-32" java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at net.coalcube.bansystem.bungee.listener.LoginListener.lambda$onLogin$1(LoginListener.java:54)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at java.base/java.lang.Thread.run(Thread.java:833)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]: Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:44 ERROR]:  ... 2 more
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:46 INFO]: [/212.37.174.9:49575] <-> InitialHandler has pinged
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:47 INFO]: [/212.37.174.9:49583] <-> InitialHandler has connected
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]: java.io.FileNotFoundException: https://api.mojang.com/user/profiles/fcae1f93bc704f9f86e33cf132e1c372/names
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  at net.coalcube.bansystem.core.util.UUIDFetcher.getName(UUIDFetcher.java:124)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  at net.coalcube.bansystem.bungee.listener.LoginListener.lambda$onLogin$1(LoginListener.java:53)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  at java.base/java.lang.Thread.run(Thread.java:833)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]: Exception in thread "Thread-33" java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  at net.coalcube.bansystem.bungee.listener.LoginListener.lambda$onLogin$1(LoginListener.java:54)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  at java.base/java.lang.Thread.run(Thread.java:833)
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]: Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
[13.09 11:57:04.870] INFO: [Proxy-1] [11:56:48 ERROR]:  ... 2 more
[13.09 11:58:01.793] INFO: [Proxy-1] [11:58:01 INFO] [BuycraftX]: Fetching all due players...
[13.09 11:58:01.793] INFO: [Proxy-1] [11:58:01 INFO] [BuycraftX]: Fetched due players (0 found).

**Comment by EnderKohle** [comment]
Dear ezTxmMC,

Thank you for your report. I already have fixed the problem. You can download the newest version at https://www.spigotmc.org/resources/bansystem-mit-ids-spigot-bungeecord.65863/ .

Tobi.
